name: Parallel Python Execution

on:
  push:
    branches:
      - rishsanyal-patch-1

jobs:
  run_python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.6'


    - name: Run Python scripts in parallel
      run: sudo apt install libgirepository1.0-dev && sudo apt install build-essential
      
    - name: Run Python scripts in parallel
      run: sudo apt-get install -y libosmesa6-dev libgl1-mesa-dev libglu1-mesa-dev
    
    - name: Run Python scripts in parallel
      run: sudo yum -y install gcc gcc-c++ kernel-devel && sudo yum -y install python-devel libxslt-devel libffi-devel openssl-devel

    - name: Run Python scripts in parallel
      run: sudo apt-get install GDAL

    # - name: Install lib
    #   run: python -m pip install PyGObject==3.44.1
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run Python scripts in parallel
    #   run: python data-cleaning.ipynb

    - name: Run Python scripts in parallel
      run: python markov_analysis.py
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-python-output
        path: |
          NY/*
