name: Parallel Python Execution

on:
  push:
    branches:
      - main

jobs:
  run_python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python scripts in parallel
      run: python data-cleaning.ipynb

    - name: Run Python scripts in parallel
      run: python markov_analysis.py
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-python-output
        path: |
          NY/NY.shp
